#!/usr/bin/env python3

"""Executable wrapper for the maintained FastAAI module."""

import sys
from pathlib import Path


def _main() -> int:
	"""Run the maintained FastAAI module entrypoint."""
	package_root = Path(__file__).resolve().parents[1]
	if str(package_root) not in sys.path:
		sys.path.insert(0, str(package_root))

	from fastaai.fastaai import main

	return main()


if __name__ == "__main__":
	sys.exit(_main())
